name: myfirstworkflow
on: push

jobs: 
  first-job:
    runs-on: ubuntu-latest 
    
    steps: 
    - name: WELCOME MESSAGE
      run: echo "Hello World"

    - name: listfiles
      run: ls -al

    - name: print working directory
      run: pwd

    - name: readme
      run: cat notes.md

    - name: Check files
      run: |
        pwd
        ls -la
        find . -name "notes.md"